### ISSUE TITLE
Home Mount

### ISSUE THREAD

**Issue by DJA777** [daleghent/nina-planewave-tools#1]
Hi. I am using the Planewave L500 mount and running it very well with NINA. For PWI4, it has the option now to enable the 2 axis, but I think it should also be able to command "homing mount" and "go to park position" That is where I start out when an automated session begins.
Also with PWI3, the fan normally stops when PWI3 is shutdown. When it shuts down with NINA plugin, the fan continues to run. Ideally that would shut down too. I am using smart plugs for power control, so I might have to look elsewhere for the fully automated shutdown of everything, The smart plugs are very cheap and quite reliable, though.

**Comment by daleghent** [comment]
Hey there,

I'm told by Bill@PlaneWave that the latest versions of the ASCOM driver that is installed by PWI4 implement the ASCOM "Find Home" function. So, if you have PWI 4.0.11 Beta 1 or later installed, you should be able to use the standard [Find Home](https://nighttime-imaging.eu/docs/develop/site/sequencer/advanced/instructions/#find-home) instruction in Advanced Sequencer. You should also see a Find Home button on the Equipment > Telescope screen, down below the Park/Unpark or Set As Park button. If you don't see the Find Home button there, then you may need to update your installed version of PWI4.

The same goes for Park. You ought to be able to use the [Park Scope](https://nighttime-imaging.eu/docs/develop/site/sequencer/advanced/instructions/#park-scope) instruction to do just that.

Regarding the fans, the Fans on/off instruction controls them via PWI3, which controls the hardware controls for the fans in the EFA module. If you don't have that and are instead controlling the fans via some 12V DC relay switch, you will likely need to use an ASCOM Switch driver for your smart plugs and control them via the [Set Switch Value](https://nighttime-imaging.eu/docs/develop/site/sequencer/advanced/instructions/#set-switch-value) instruction.

**Comment by DJA777** [comment]
Thanks Dale,

Very timely here. I am working on that now. I am using PWI3 to control the
fans. I tried adding a 10 second delay after the command to turn off the
fan and that seemed to work. It looked like it was closing PWI3 so fast, it
was closing before the instruction to turn off the fan.

I will have to check my version of PWI4. Now I see - I didn't know there
was a find home in NINA. I wasn't looking carefully enough. I did confirm
today that finding home is essential,, Without it, it pointed in the
opposite direction and the dome rotated to where it should have been
pointing, I have been just running the shutdown sequence to get everything
to sequence correctly. I park the telescope looking down to keep dust and
things from falling in the tube.

You are going to like that telescope. I am impressed every time I use it.

Dave

**Comment by DJA777** [comment]
It looks like I can't get it to find home - or as PW calls it "Home mount".
I set up a simple test . Connect to PWI4, enable the two axis, connect the
telescope, unpark telescope and then find home. Everything seems ok, but it
does not move to home and displays a red X on the right and a red ! on the
left, which says the telescope does not have home capability.  I downloaded
the latest PWI4, Beta version 9.

Any suggestions?

Thanks,

Dave

**Comment by daleghent** [comment]
Ok, perhaps the Fans on/off instructions is finishing too quickly and aren't giving PWI3 enough time to transmit the order to the EFA. I can put in a few second pause after issuing the API command to PWI3 to give it enough time.

As for mount homing, I neglected to mention that, per ASCOM, the mount must be unparked for a Find Home to happen. Could you try that sequence again, just adding an Unpark Scope instruction after the axes enables and prior to the Find Home?

**Comment by DJA777** [comment]
I will do that, but I may have tried that already. I will do it again and
let you know,

Dave

**Comment by DJA777** [comment]
I tried a test run.. Start PWI4, connect the 2 axis, connect the telescope,
unpark scope, then find home. It is not working.

When the sequence hasn't started it says it is not connected. WHen the
sequence starts and the mount is connected, it says " telescope does not
have a home location capability". Somehow it is not getting that fact from
the PWI4 or something. I can go into PWI4 after NINA has started it and do
the home mount operation ok.

I hope this helps. I can do almost everything else to get the system to
start up and run without leaving it on. I am also working on a way to power
the equipment through NINA. WIth a former Sierra Nevada Corp engineer, I
have gotten NINA to open the dome shutter doors using the external script
function. That works great now and has been for a couple days. The weather
here is preventing any further testing of that.

Dave

**Comment by daleghent** [comment]
Ok, thanks for trying that, Dave. If you're getting that error message, that means the PW4 ASCOM driver is not advertising the `CanFindHome` property. You might want to ask PlaneWave about this because the release notes for PWI4 states that the function was added in 4.0.11 Beta 1. You can find the release notes [here](https://www.planewave.com/files/software/PWI4/CHANGELOG.txt). This behavior might mean that the function is broken in the PWI ASCOM driver, or your installation has an older version that wasn't upgraded with the main app.

For the fans, can you try putting in the Fans (off) instruction followed by a "Wait for time span" instruction of 5 seconds, then the Stop PWI3 instruction? I am interested in seeing if that 5 second pause between issuing the command to PWI3 to turn off the fans and then killing the PWI3 process is enough time to actually make the fans turn off. If it is, then I'll bake that 5 second pause into the instruction and make a new release of the plugin.

Thanks!

**Comment by DJA777** [comment]
Thanks. I will contact PlaneWave and see what they say. I did put a delay
after the fan off command and that did work. I am not sure about the time.
It was either 5 or 10 seconds. I can check that out now and see if 5
seconds is enough. I think it is.

Dave

**Comment by DJA777** [comment]
I tried aa little test run with the 5 second time wait after power off the
fans. It worked and shut down PWI3 after.

Dave

**Comment by daleghent** [comment]
Hey Dave,

I've made some changes to the Fan control instruction, where it will set the fan state and then poll PWI3 for the fan's status every second until it matches what was set. It'll do this a maximum of 10 times before erroring the instruction. I've also added some additional checks in the event that PWI3 is running but isn't connected to the EFA, and is thus unable to control the fans.

Grab the attached ZIP file, unzip it, quit NINA, then copy the `PlaneWave Tools.dll` file over the existing one under:

`%LOCALAPPDATA%\NINA\Plugins\PlaneWave Tools\`

Then start NINA up and give it a try without the "Wait for time span" pause you put after the Fan Control off and Stop PWI3 instructions. Before starting the sequence, you might want to set logging level to Debug in NINA so the logs capture some debug output from the plugin in case there's an issue. You can do that by going to Options > General and set Log Level to Debug. You can set it back to Info if everything seems to work.

Thanks for testing this out.

[PlaneWave Tools.dll.zip](https://github.com/daleghent/nina-planewave-tools/files/8127310/PlaneWave.Tools.dll.zip)

**Comment by DJA777** [comment]
Hi Dale,

I will give that a try right now. I work on a Mac, but the observatory is
on a windows mini PC. I should be able to do that remotely by getting my
email out there,

Standby.....

Dave

**Comment by DJA777** [comment]
Dale,

That works. Normally I have PWI3 set to turn off fan when the program
closes. I tried that without the top fan command, but the fan kept running.
Putting the stop fan command before stop PWI3 - no wait for time span -
works fine.

Dave

**Comment by daleghent** [comment]
Thanks so much for testing this, Dave. I'm glad to hear it's working out. I'll roll this as a new release. 

As for mount management, I hope that I can get a few questions answered by PlaneWave regarding model creation and related things. I'd like to get an L-350 mount to go with my CDK14, and I'd really like to be able to create dec arc models for it on the fly from within the sequencer, like I can do with my Astro-Physics Tools plugin and my A-P mounts.

**Comment by DJA777** [comment]
You’re welcome. Bill Dean at PlaneWave is good to work with. They are supposed to be working on other software for building the pointing model without having to buy MaximDL. That’s quite an expense. It should be very straight forward with NINA. I haven’t changed telescopes on the L500, partly because I’d rather put that MDL expense toward hardware. 

The L500 is great for 2 telescopes. I have the CDK17 on one side and a Explore Scientific 127ED on the other. The profiles on NINA make that work well. 

Dave
